"""empty message

Revision ID: 709a48840d5d
Revises: 572277490863
Create Date: 2022-07-18 15:00:06.081667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709a48840d5d'
down_revision = '572277490863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('usd', sa.Integer(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('rub', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordertable')
    # ### end Alembic commands ###
