"""empty message

Revision ID: b88d122c8e2b
Revises: 709a48840d5d
Create Date: 2022-07-18 15:02:24.735431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88d122c8e2b'
down_revision = '709a48840d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('usd', sa.Float(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('rub', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordertable')
    # ### end Alembic commands ###
